services:
  mongodb-course:
    image: mongo:7.0.4
    container_name: mongodb-course
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_course_data:/data/db

  mongodb-chat:
    image: mongo:7.0.4
    container_name: mongodb-chat
    ports:
      - "27020:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_chat_data:/data/db

  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak-db
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  user-db:
    image: postgres:16-alpine
    container_name: user-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user-db
    volumes:
      - user_data:/var/lib/postgresql/data

  order-db:
    image: postgres:16-alpine
    container_name: order-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order-db
    volumes:
      - order_data:/var/lib/postgresql/data

  exam-db:
    image: postgres:16-alpine
    container_name: exam-db
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: exam-db
    volumes:
      - exam_data:/var/lib/postgresql/data

  payment-db:
    image: postgres:16-alpine
    container_name: payment-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payment-db
    volumes:
      - payment_data:/var/lib/postgresql/data

  purchase-db:
    image: postgres:16-alpine
    container_name: purchase-db
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: purchase-db
    volumes:
      - purchase_data:/var/lib/postgresql/data

  safety-db:
    image: postgres:16-alpine
    container_name: epp-db
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: safety-db
    volumes:
      - safety_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev # Modo desarrollo (rápido y sin HTTPS obligatorio)
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      # Credenciales del Super Admin (Para entrar a la consola ya mismo)
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    depends_on:
      - keycloak-db

volumes:
  purchase_data:
  mongo_course_data:
  mongo_chat_data:
  keycloak_data:
  user_data:
  order_data:
  payment_data:
  exam_data:
  rabbitmq_data:
  redis_data:
  safety_data:
