server:
  port: 8087
  error:
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: purchase-service
  config:
    import: aws-parameterstore:/config/application/,aws-parameterstore:/config/purchase-service/
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
  cloud:
    aws:
      parameterstore:
        region: us-east-1
      stack:
        auto: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.logistica.purchase: INFO