eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  security:
    oauth2:
      # 1. Configuración de CLIENTE (Necesaria para TokenRelay)
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/industrial-safety
        registration:
          api-gateway-client:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: ${SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/industrial-safety
  cloud:
    gateway:
        # 3. Filtro Global: Pasa el token a TODOS los microservicios
      default-filters:
        - TokenRelay

      routes:
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/v1/course,/api/v1/course/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users,/api/v1/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders,/api/v1/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments,/api/v1/payments/**
        - id: payment-receipts
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/receipts/**
        - id: notification-ws
          uri: lb:ws://notification-service
          predicates:
            - Path=/ws/**
        - id: notification-ws-sockjs
          uri: lb://notification-service
          predicates:
            - Path=/ws-sockjs/**
server:
  port: 9000
