spring:
  application:
    name: chat-service
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: mongodb+srv://ricardoipalomino_db_user:7yeM063DgLJoyMV6@cluster-industrial-safe.vjhcknn.mongodb.net/?appName=cluster-industrial-safety

server:
  port: 8085
  error:
    include-message: always
    include-stacktrace: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
