spring:
  application:
    name: course-service
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27019/course-db?authSource=admin
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/industrial-safety

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket-name: ${AWS_BUCKET_NAME}
    stack:
      auto: false

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
  region: ${AWS_REGION}

app:
  management:
    email: ${MANAGEMENT_EMAIL:gerencia@industrialsafety.com}