keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: industrial-safety
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}

server:
  port: 8081
spring:
  threads:
    virtual:
      enabled: true
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-db:5435/user-db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    stack:
      auto: false

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true