spring:
  application:
    name: chat-service
  threads:
    virtual:
      enabled: true
  config:
    import: aws-parameterstore:/config/application/,aws-parameterstore:/config/chat-service/
  cloud:
    aws:
      parameterstore:
        region: us-east-1
  data:
    mongodb:
      uri: ${MONGODB_URI}

server:
  port: 8085
  error:
    include-message: always
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized